[project]
name = "hebrew-calendar"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "astropy",
    "pytest",
    "pvlib",
    "dash",
    "dash-bootstrap-components",
    "gunicorn",
]
